package puzzles.year23.day1;

public class Part2 {
    private static final String input = "23krgjlpone\n" +
            "kfxone67bzb2\n" +
            "8jjpseven\n" +
            "236twoknbxlczgd\n" +
            "sevensrncljm5zmvvrtthreejjd85twonepvj\n" +
            "1dgzljrtcndqqrqkgxseventhreessnthree\n" +
            "s2eight6bhshvmsevensix\n" +
            "5tpbsrf\n" +
            "two35kxjtnbhxrmdhbgzeight\n" +
            "khgdlljfjxt6sevenfour35pxone\n" +
            "qvztdsix2\n" +
            "6lsgzmjtjrseven8cnbnpgd\n" +
            "three1sk4hnine\n" +
            "sixmqhg5tvbvlhtzxgpfqlzone9\n" +
            "fljgbjmccvpz67one\n" +
            "5six3four9nine8\n" +
            "twomtdsgxdxgc898sevenvml\n" +
            "4xxbgkksppdtwo37\n" +
            "67sixflmzrzxtwoqnkgskpcgpdmsh\n" +
            "9hxfxqjn1twoqgkcjdgbjr3\n" +
            "fourbsqr7bktkbqbdlpfour\n" +
            "6pzntcxtpdjvhjmrbthree882kcsbhl\n" +
            "fiveffjfkcz5\n" +
            "8bxglmkfskvvqzonethree7twonjqlq\n" +
            "ssdxrgjncdxscf8threetfcgknm9three\n" +
            "3ninefiveeightzxbhtltjv\n" +
            "bmnzsgmgcfour8ltfmthree\n" +
            "rmsmtbfh4eight2\n" +
            "heightwosixthzdf7gdtllhsnfive1onemfcqkqfqkj1\n" +
            "1fourthreetpmqqtzgtwofour\n" +
            "rhckmzd1pmmgthree2fivesevenseven\n" +
            "14ldpdc8five62hff5\n" +
            "psblg3\n" +
            "17seventhree3ntcnbddnine9five\n" +
            "tc5sixsixfivepxtxgcgjqxgmnonetwo\n" +
            "578nlsix\n" +
            "fourtwofdxcjgcgdonedpmzseven3four\n" +
            "six3qf26eightfive\n" +
            "one55two2six9fqgzc\n" +
            "fmbxsxhtzcseven7\n" +
            "mvbvzlznkvmpxxrsdtfivekddldmfg4lxzj\n" +
            "bqjmdd7neightvsbrdf\n" +
            "8m6nb\n" +
            "foureightljkmbgt2\n" +
            "shsfiveqhtr8eightcc8sevenmkxf\n" +
            "sixnine6seventwo\n" +
            "sixfive53\n" +
            "bvtfrhkxkzslgsevenfiveninefour2two\n" +
            "four2dmltrbv\n" +
            "vqbdbhseven1drdncbgscfncgtdd6\n" +
            "73bonesevenone\n" +
            "foureightpbxbfsqtdffmxsdrzpx5fournineeight\n" +
            "threehfldfggkqbfsxpvvcjnthree8nkdvsxvd59qmkpzbn\n" +
            "26tlzzsbdthree877eight\n" +
            "7eightthreetwonepzk\n" +
            "tstrbvfppnineninetnbgrdone9twosr5\n" +
            "7threeeightsevenz\n" +
            "5three5nine\n" +
            "nine1ninecmj\n" +
            "699six3sixnine2d\n" +
            "2qpfrbxpds5nineeight\n" +
            "five8lttz39vd\n" +
            "ntlznczfone7ninesixxtxbkvpkonebmbc\n" +
            "frpcfbgnceight943oneseven\n" +
            "8ninedcspc3qkvjsvkhj33\n" +
            "nine8msxvtnkzqhhnj128\n" +
            "sptoneight5jmvqdkfvbgfour3one\n" +
            "eightgvzhdhrzxrfronefive9\n" +
            "nine49\n" +
            "one1vgdmlfgdh1eightwodx\n" +
            "threemsxhlzj9four485\n" +
            "9onelvcqrzxjtthreetwo\n" +
            "3eight21onetrvvnkknqtjblmb8hcxgjk\n" +
            "ftlbbc3twoninetwonine8four\n" +
            "lbxzfjlzgnkcx1zf3kccqtrxfsktpgbdjsxpjdt9\n" +
            "12seven6lzpckvcl\n" +
            "2one8dbppqninesmj\n" +
            "3lqkzspntkqbk7twodhshtdbmxd\n" +
            "xscdclmeight6nthreephsgcdbbb\n" +
            "nine9bpdxz\n" +
            "8onethreeninethreetwofourzkq\n" +
            "7trvjqvrdfjrpr4sevenblrhxpmvfour\n" +
            "nine4pmmrccv7\n" +
            "579eightfoureightsevenfgpbdvhmeight\n" +
            "fourgdfspclskp41fivethreeoneightf\n" +
            "one41nine4onesix87\n" +
            "ninesix19sevenpkhrdxlkmgjvfive\n" +
            "86lkqtmcpthreetwo1\n" +
            "4mbtkzzghps1five3\n" +
            "two73prtsevenxmsix5\n" +
            "73dmjhjfivedtjlqeightvkktm\n" +
            "sevenxkfrsggjfive9\n" +
            "fivefivenine9fourthreelbgclzfive4\n" +
            "99xdddfznnl\n" +
            "ninemrgssixnine1\n" +
            "7two68px36seven5\n" +
            "45crzvfqnrjc6onemnsv\n" +
            "oner4\n" +
            "7skqhfour7\n" +
            "7npffnlqtwomzkqjgrbtcfj\n" +
            "threemrtsmxeightfourone3rldgtn7jjfjncrnd\n" +
            "eightrtchrvjsjpdjbjpfqbksfclxdsbgfbghmbvd5\n" +
            "six5two9three\n" +
            "ninetwo1\n" +
            "9sevenhvvqznhnnnpjninesix3dqxrlqlfour\n" +
            "cgtqtnckqbsrlncdfourfourvc76\n" +
            "3fourtwofive6ksblffhpqoneightsz\n" +
            "tbnn62\n" +
            "7nxpktbvrrltjthld\n" +
            "5vnlcbseven\n" +
            "1five3\n" +
            "bpgknpmjeightonepxd8fiveone1twonekz\n" +
            "eighttwoeight2bgzbscvrj8\n" +
            "3fourfour8\n" +
            "941dxzpxjp\n" +
            "rkzzrfiveqrbrx12kseven\n" +
            "twofoureightpqpscvhlvbxgfpbrrkvc6sixxzhn\n" +
            "3776\n" +
            "nrtflrbcpm4hjdcthreercppzt1fddjjcbsnq\n" +
            "zddmp2\n" +
            "3krbkrrsqfive5\n" +
            "5vdvgctvv\n" +
            "9six58sixt9six\n" +
            "ninenrdbvhqdgz79one\n" +
            "jpprfgxthree326ckxnqthree\n" +
            "1hczkfhmsixhrkkkqjcbeight1zbgcxzrffr\n" +
            "fiveqeightkhdrsqstd1\n" +
            "615zmzrmbmkvbz\n" +
            "five3foureighttwosb7rpqsxmhzjj4\n" +
            "999kqtxone\n" +
            "lsr6qccnmfgzdrqmzrshlkthlm34five\n" +
            "99four\n" +
            "six2xnxtd\n" +
            "8fourrgzq9ktpddqkl2nineseven\n" +
            "8threelhtfzzc7oneone7\n" +
            "21bvpqphthreegthrzjqvcsixone8\n" +
            "dcrtjxzbkn8931tggkzz\n" +
            "9rlllvfbqllvhlqkhpzkrrsktnfjpbqgxr\n" +
            "zzfjjcrgjm8sixonekmnvffznine\n" +
            "5djrcdjckjf6\n" +
            "4msdct5\n" +
            "one1six\n" +
            "71five\n" +
            "jmgpmg29rrhkz9five75\n" +
            "299fmbpctwosix8vxnmvqlktlnxdb\n" +
            "34qjjq8nine\n" +
            "fiveeightcvd15fk\n" +
            "qxbnfptcmszqqspxxnnnjfivesevenrts8\n" +
            "seven4ztqcxmrmgdkcbd8\n" +
            "2pkfxntlfivetwo5eightwovf\n" +
            "dhgfbksgjn56\n" +
            "fiveeight1128onesix\n" +
            "7four3four941fourtwo\n" +
            "sixdhjgvnqlngvflnnxpbjlctkvjfbglseventwoj6\n" +
            "lrkmgcngk7one\n" +
            "22fourbbtlhrcvfp\n" +
            "six5kxrtwo65\n" +
            "8ltnfnkfsfx\n" +
            "9cpkprmcdzteightrvseven\n" +
            "ntsqp2vqcs7hsjdbvqreightfourtwo\n" +
            "nine32fivefive3sevennine\n" +
            "5pglbjdsnblthreeoneeight8\n" +
            "qpj44nine3three5\n" +
            "8hxzh\n" +
            "four3five5\n" +
            "3zmnskk\n" +
            "jdfbznineonefive41\n" +
            "5893xhmflpgfour1two\n" +
            "cf6\n" +
            "1threeonesixtlbleightspzxmgppgd\n" +
            "zxjgrpnvb17onekn\n" +
            "bvvrbnjdlghjhfn78qltkmc6zsfive\n" +
            "7twonen\n" +
            "22gkmr\n" +
            "3xdkbf3four\n" +
            "chzprgpskqmfhonercxxn1four\n" +
            "sevennmnjhhlqmctz5fourreight\n" +
            "twoseven64hndfive\n" +
            "fouronekhl2sevengchgtnrrsevenx\n" +
            "sevenxptwo77dvx9\n" +
            "threegtddhpveight14jhbjpnvxsk\n" +
            "81nzmcksj4mqkspfmm\n" +
            "seventwofivefourhcfour6threefive\n" +
            "8five8four\n" +
            "qcqllthreetwo39nzltgfzv\n" +
            "zt5\n" +
            "four1twosixv6jqxcsbmjh\n" +
            "xsvtllxbrm6525onetwo\n" +
            "onezgsix79bbrrfneight9\n" +
            "gtwo6five\n" +
            "seven483fxnsrqbgqdm\n" +
            "4ffiveseven8vmspqnhxtninefour\n" +
            "bcjlseven4679bpm74\n" +
            "seven43sqtmsevenqkpsix87\n" +
            "dhbfbspfour77eightonesix43\n" +
            "jhhbphj1\n" +
            "5kbzkrqxclfvndzhppcsjcgqtqlqbh4\n" +
            "sixrmzqqxzeightxzglghnnkfmvrlgfoursix4\n" +
            "eight1five6two\n" +
            "32fourfivesixsixtxnvzdfpnxrp\n" +
            "szoneight875jqlonecchndzcgsk2three\n" +
            "fqnqpmx46\n" +
            "qsevenseven17mplkggslltmddc\n" +
            "chbfbjctpkdtmkjksct1ninetwoeight9vbnv\n" +
            "eight2two7xfrzthree\n" +
            "5hdkpdgqcdldfjjtzcqtwobdlxcrfour\n" +
            "ninetwodqc1three1xppmbcs8rsrgmp\n" +
            "2vjnvdv\n" +
            "nine24hnqfhsevenvsvtzssbnine6\n" +
            "lsix5one2sevenfourmstjtkq\n" +
            "vtwone3hndkjqseven\n" +
            "two726dbqvp3glxf\n" +
            "eight1six\n" +
            "1clfjfvscz22qrcqlbdrt\n" +
            "88fivegsqprddzl4rzmcpzrp\n" +
            "k5qsflbzblsszlvxqxvjjbffiveseven\n" +
            "56943\n" +
            "gtzm7fournhhmdrgg9x\n" +
            "cxhtfrpvrtwobslfqnvvs56cfnmqgcz75mvzkcf\n" +
            "36gxlgbbdh89\n" +
            "rlhcgklnt56brh8ffnd5\n" +
            "94nine3\n" +
            "6qrzcfmnzvfour6six\n" +
            "tzcndx5zqfour\n" +
            "gtxxms528four72\n" +
            "sevenbsxmddjl2three1\n" +
            "threenine98hrgjclplf16\n" +
            "fivegptznzbzvpdnlqqsdd94gpbflttzone\n" +
            "gcnoneightmprf8seven4nqcvjbvq66\n" +
            "kbbttnjp5htvkgtwo37tnjdrvvg\n" +
            "eight9mrskskghseven2zcrktxkq\n" +
            "gblxnineone6fourkmvjsm\n" +
            "jzrrtzmpseven8\n" +
            "eightnine87smpxstvxfivenine\n" +
            "3ninenine\n" +
            "8nine766onetwonldmpzmcsmz\n" +
            "cmlqljxfhhv6hzk\n" +
            "bnhcmtjhcninethreegflnkzxgfqntzdvrk3\n" +
            "twoeightfive9eightwov\n" +
            "eightvqq45gtj95\n" +
            "4seven9\n" +
            "seveneightlqhfr66csshcmxfckt8\n" +
            "eightfour6\n" +
            "1qsk4six\n" +
            "hcdvcgrhzeightthree52hsix\n" +
            "lnine6five\n" +
            "5four3seven\n" +
            "9sevenmmxtvxrxxnvdh33kkpgjbhgsr6\n" +
            "sevendkninev542\n" +
            "dzxmxz71xsfivefour\n" +
            "2ninegmvnmhm9ninetwoone5nine\n" +
            "fournine337gt\n" +
            "two7threeshffour9\n" +
            "sixtrxxh94bjxgdjsixlrmbfsvptjvcrpphtwo\n" +
            "zzvxmbnvslnine9sixthreenq4seven\n" +
            "8twovbxdqjrz\n" +
            "fivetfrcpq74nine1\n" +
            "cnkkpqrnhdthreenonesfzbttgf2llfpl\n" +
            "five6foursixbgdvf6\n" +
            "sevenxxfkltwo7q\n" +
            "six969jxvr\n" +
            "threevxskvvheightsix7sevenfivemqzvh\n" +
            "41xgld1twodmc3four\n" +
            "2gltghqkfourqhpqtftwovseventd\n" +
            "8ppgrcnf\n" +
            "953jjtsixhjkddzjvkcr53\n" +
            "359\n" +
            "33eight6rksnqfjxrqonethree\n" +
            "four7nplv\n" +
            "3nvrncjlg65\n" +
            "4xxzpnine7\n" +
            "73mkmvccgxhdp\n" +
            "1qcpxjqrjgrpjbzcfour22\n" +
            "6qcpgmkxprpthree8\n" +
            "fourf3eight5\n" +
            "xm86\n" +
            "xpvtptckgneightfivetththree6three3znxh\n" +
            "5l\n" +
            "jqtpksdvgmncftjxr17five6zznxjbmzr3\n" +
            "4nine5\n" +
            "ninetwolhdzlmnglp6sixjljlkhgtggqv36\n" +
            "gkthkone8\n" +
            "eight46\n" +
            "97jfthree\n" +
            "qgltwone6seven6one\n" +
            "zljlzdbtcx6threenine7nine\n" +
            "hctvdcpvsb12\n" +
            "2threesevenseven\n" +
            "hjmzlzlxltninefourbfnzqqhlq9fourfivejhvc8\n" +
            "threetwotjsnfjjqgdfoureight5crjthmlshhdtsix\n" +
            "two5snkqq11sixthreemhthree\n" +
            "8tworzoneqeight8nine3\n" +
            "827qzfrjlpfournine6twofive\n" +
            "h93\n" +
            "7nnfourthreenbsqjzsttwo81\n" +
            "8lbzftbn\n" +
            "cgjrfkgone8\n" +
            "dtktb1kfkrh\n" +
            "eight3three57ninethree\n" +
            "7six7fkcgdzjxfive\n" +
            "5lzxczrxqnrthree\n" +
            "cgjxcmnx2273\n" +
            "two5tqpjxzjqdsgljrvkc4sbkdl\n" +
            "nineninedhvqj4fivesrk6m1\n" +
            "jmpnhdjkcdpffq4\n" +
            "8ssix8three\n" +
            "fivethreetwo11ninevkqnineeightwof\n" +
            "9mxdzbhqsixfstccqkkbtkmplrhqknfxnpdnhzhstwo9\n" +
            "eightnine18sr24\n" +
            "3chxnlcrbjbq9seventwodbrthreefive\n" +
            "647dhxkdgfcpppcrg6nxgsbgfm4\n" +
            "threepnfsjdfxvcseveneightsfjvmzvklpfour1pjfsr\n" +
            "3vnnzqhsplqznine2mbg\n" +
            "hs7\n" +
            "fctwone8ninethreetwo\n" +
            "zjvgtjnine6oneeight7tsxrqseven\n" +
            "one4fiveninefivesixfourtngb\n" +
            "threefivethreesix5xfjmj28fntbpj\n" +
            "2xzpfour2qjxblmh4\n" +
            "seven9ninerzhsqjnbzmmlflpmvszdqg\n" +
            "9kfnvmbpk8ninefivegpcxjvtrxhtggnine\n" +
            "83nine4onesix1jgbttcd\n" +
            "fourthreetwonine5fivebhgnckjtzjhgdlb\n" +
            "foursixmfvsevenqdgsix1slmrgmvzhr6\n" +
            "zfxoneight7threethree\n" +
            "sixsixvtgnsix7one66\n" +
            "jkpvffoursevenrvzbd1sevenlntvggdk9\n" +
            "onetwo6one6\n" +
            "2pvg5nine21\n" +
            "pzvhgcppglsxfbnzsixninethreecjpzxgchpfour31\n" +
            "twolczflqrbk4rgcone\n" +
            "sevenntqfdnqgbrmtxhssqkzdknvcttzlsone8jjthree\n" +
            "onethreekglkgbxhtwosdkcfvrffdlfntslkvblpq7\n" +
            "mtjzjxkxb743two4tlgkzslhnnine9\n" +
            "zpqvnine3\n" +
            "ppkmh3hfive\n" +
            "sevenfiveonenine63\n" +
            "9t3eight3dtgrrjzj1\n" +
            "5jxjmnsn\n" +
            "lpgv5twonem\n" +
            "lzcrmbseven5\n" +
            "k22\n" +
            "threeeightqnine7jbhcrdfljdlqseven\n" +
            "fivenqeightninezmrm2vpdptlrnine\n" +
            "75eighthmj93threeeight\n" +
            "four4twoninenine6threegbfhlxgg\n" +
            "21zfgxvfmggh39\n" +
            "9xqxphjzqkkfpvsmbjzpv8nineeightdcg\n" +
            "16five5ptprsjtp31five\n" +
            "two5hncjfhzsbeight6tdkhdfqttsgkbqlqdmfchcbnmxhtm\n" +
            "hlqxqmfjmsvmzpqmkh31\n" +
            "twotksfsttbvx7dtfdgoneightx\n" +
            "two6gzxplc\n" +
            "pgthreepsvxlqkthreesixhrkgdf9gpmrgzl4\n" +
            "28sevenhlljbkbz1\n" +
            "4nine5sevenfourccdsmzrlkmshfslzpkm\n" +
            "rqhns85fnrkninesixonex\n" +
            "czoneightjffrjhvvtrqxmvmmmspkhphr93eightfive2\n" +
            "rnnvrdgjtvnoneeightsix61ninehgxfplfbbd\n" +
            "23xsxlxlsz\n" +
            "mhjtxrhfive9six\n" +
            "qddgntfdthreeone9three286five\n" +
            "3hqszrplfjfivethreefive\n" +
            "hzjnpktseven9hlbheightfour\n" +
            "2vpksixthree\n" +
            "one5hjgqtpcjhntpxfxkf4fourtwo\n" +
            "dcrjgbcfjvnnmxbfv7lhxcs\n" +
            "sevencsm8\n" +
            "seven7seventhreetwoml5\n" +
            "htwoneonenine4\n" +
            "rlllkslz6sevendfth2seven\n" +
            "twoqbcconebldvhssnrqgn3jvpfk2\n" +
            "one4nineseven3two\n" +
            "4nine4\n" +
            "zjbfxbsevenqlbnkd6\n" +
            "cktbzrsevensxnljlkr8cldjkcpqlkkxqzsp\n" +
            "mxdbddrtz3tz3\n" +
            "1nzcphbgtsgmpprceight2pxjjrttglllh5\n" +
            "four5zj21sixseventhreebs\n" +
            "6sixvsfggqcn\n" +
            "4kzfctjjmrxttlhc\n" +
            "jhoneightsix23jklvhnqxzhjsr\n" +
            "26six1threeeightvnkdvqqkxs1\n" +
            "six7sixzzhfmqpqsevenxbnine\n" +
            "jfsh355\n" +
            "7347eight\n" +
            "4qrmvkfhzmrqgk6dkx\n" +
            "txnfnvffxfkthreethree72ninenlftwo\n" +
            "2nine8nine\n" +
            "fnhghhrqq6zxcckxqpmtwo6two\n" +
            "one44\n" +
            "six7vf8fourrvfvljcm9four1\n" +
            "7four8tjlhrcq\n" +
            "6fivehnfoureightfivefourfive\n" +
            "818threethree\n" +
            "kqzqcsdseven4m\n" +
            "4eight47pmhssvj71\n" +
            "6bjd762nine654\n" +
            "eight3nineone2\n" +
            "seventwoblkspmfour2eightthreezjpxxxkr2\n" +
            "zsjbctgteightcjbqvs9\n" +
            "4jljnqrfjjbbvzdsixonetwo2\n" +
            "qcqrnfxkbvndztjx91bshtrjzq2\n" +
            "5five6sixthree\n" +
            "78thvkljsxllhq\n" +
            "nine24cdcmbdjrxntwo\n" +
            "kvthree7\n" +
            "fourninectzcszglpk457fourxnsbtmmlc6\n" +
            "two2lx59gdsjjvneightfiverk\n" +
            "five86\n" +
            "2hznine58\n" +
            "sdbjxkfiveone23two2eight\n" +
            "5jxlntcpslksfmfive2\n" +
            "fourtwofourjb5xxknnpr\n" +
            "seven9hgbnqfgvst\n" +
            "7kbcv\n" +
            "bjtdxlknkone6five\n" +
            "zkzt37dlffxhssfcv37rldkcb\n" +
            "137six8znvqtmkmrb\n" +
            "6sixkmthreejglqsrvckndncjbnf\n" +
            "5bxhvfdqklf\n" +
            "1ksvcdrbccffour\n" +
            "rvqhjb1jbqmnv\n" +
            "five4dlnhqdlnmrpsksnine\n" +
            "eightnine9\n" +
            "ssrgz57four1fivehqoneightbrf\n" +
            "9tjhxfjjtrfive\n" +
            "5twoone5sevenfive2twompr\n" +
            "vpgnnksmdppgg9onekdgrfddkxgz\n" +
            "fhtkdcs9lbgrh9eighttwo1\n" +
            "four9eightnine\n" +
            "pvz5four\n" +
            "oneeightsix8dcxmxnine2\n" +
            "5twotwofour54twonine\n" +
            "4386fivefourthreegjmcjsvs\n" +
            "smrbxfive71sixfour\n" +
            "ninethreetwo7\n" +
            "zzkpxqf5rqjc61gfoursix\n" +
            "c6\n" +
            "seventworlgbcftnl652threethree\n" +
            "32qqhkkxtqmgqjpcscnhlplbcnfivefive\n" +
            "tkprrcc7rhsldfjpnthree\n" +
            "six8twotwogqrn\n" +
            "4chmkqfive\n" +
            "3cfqxfour6rcjmsl4five\n" +
            "ttbskeighteight21four\n" +
            "4kxsfxhcxonesix58\n" +
            "qls4six\n" +
            "56sixtwo73five\n" +
            "6czmnvvqfk88jmnsbjeight957\n" +
            "threefourrflgnktwo2\n" +
            "1one8\n" +
            "fourrhltmg4sixmgn9three\n" +
            "eightrdztlhdxheightsqdckpc3jfnljdfjgj\n" +
            "qxglhfcqlm42xktg84fourseventhree\n" +
            "one72threer\n" +
            "9eightsixjqndxbx\n" +
            "795nrmlvntwo7\n" +
            "hptzszgtknine4779\n" +
            "1btvfjjzkr6onetwo4pldtcqmpbhm\n" +
            "1four214three\n" +
            "4ninethree7twothree\n" +
            "s4\n" +
            "seven47eightsix\n" +
            "4six22\n" +
            "jctwonethree4kznninetwotwo8\n" +
            "54sixlbnjf26kcssxrqjf\n" +
            "pdfpcmv6sevensixztcrxbpxxk3five\n" +
            "1six1hgdxsq5rzfhttcr94\n" +
            "twofive86onetwothree\n" +
            "sixmxssdpcdmm2l11lxgkksqtlp\n" +
            "63fourseventwo\n" +
            "cljldbmhmvseven925eightthddgtkplk\n" +
            "one8seventwo12five\n" +
            "541seven97rshxfvqrlztx\n" +
            "tlxlzst5ttpd\n" +
            "g4sixtwosixpvsqqrkntlrf1\n" +
            "jvdpjdgskqtt8cks2gbghxzmtc98\n" +
            "sixqhzsixtnvfgm4fourzqzkldjstwol\n" +
            "hktmt46\n" +
            "six98onenine\n" +
            "tworxfivedltzldrdbx944four\n" +
            "92six4brhgzc\n" +
            "ptgkqcsxv7jmshz8kqxjxsrzc52four8\n" +
            "mmfrvcpbt1four\n" +
            "bnnqtxrq4four554zmgfmzcttb\n" +
            "2zzp4\n" +
            "k883sixthree\n" +
            "7gdjdxdhfvptkhlttwof2sheight\n" +
            "5fourpbntlnrs6eight5six\n" +
            "sevenone54\n" +
            "98czxflgbnmrninefiveone31\n" +
            "429ninennkhtzveight7lqmzdlgg\n" +
            "qp1twodnxeightsix26\n" +
            "97kqkjsmkqhzbdpf\n" +
            "rplxsjlsvdplsndzxoneddlvc6\n" +
            "threeskgfpvffkz2\n" +
            "687zrlqlhdcrseveneightsixsix\n" +
            "hhnfzkn6lhbxrkbm4four\n" +
            "pmg9dnnzg3\n" +
            "fnlgprdjvtwo2two9six1sqkhnv\n" +
            "nvjgseven6threehvpgpljgthtltsmssdvjhc3nine\n" +
            "fbmpsjrlknineseventhreeeight6br\n" +
            "1qhtqxnbtceightjonesmkp8\n" +
            "zoneight2svlkjmxzjjone3njjqtcmp\n" +
            "3one7\n" +
            "seven2fournine4seven\n" +
            "kdhqhhpfiveeight9\n" +
            "4threelnlrbzreightonenmrf923\n" +
            "1qjllnmjjpjtwosixfourfkpqfnjfive\n" +
            "eightonezbhfj3nlkrzrtwo\n" +
            "2twoqzjvceighthql4sixsczgvbl\n" +
            "threetwodt66\n" +
            "knj87twogqkkznrpmqhloneightdn\n" +
            "867rfvjx6857\n" +
            "one9eightjsgj6\n" +
            "sf96nine\n" +
            "eight5mbfjcvdq3236mbhzklbzxgkntlmzdtz\n" +
            "5hqtxftqsixthreeqsjbsbpvtsnqrgjnzznkg\n" +
            "2847\n" +
            "sevenseven4ztqjpmbhs9f1\n" +
            "dmpnjkttdnjmqvsnfivesix4threeoneskr\n" +
            "two339\n" +
            "twotsnfkgkqls9\n" +
            "73lhfseven\n" +
            "gpcc5fivejtcfxeight\n" +
            "75fourdvht1\n" +
            "qcnone5gdfrcsmhtqmgjnhsixhzzxjpjfxsrgslgq\n" +
            "ninedvbzngtv7rtb4ksrmveightwofjn\n" +
            "qqsxhtsvdseightfive9fivesix24\n" +
            "36\n" +
            "tnrklrvtthreetwoblzfour5\n" +
            "eightfoureightoneeightdbppfjtwo4\n" +
            "seven273twoone\n" +
            "44qfcsmpkv9nnfg4three7\n" +
            "3ninenine\n" +
            "onegfsnpc4kzlseven\n" +
            "threenpzfzsgqvnsevenbkzrnnhdeight1\n" +
            "dfbtq2fourfour\n" +
            "five6oneseven5txqvzzblkeighttwo\n" +
            "fivexxgpptkfkfour6\n" +
            "nhbnctlptjfvqteight7fivetjklvxnrvpsjf\n" +
            "twothree6eight\n" +
            "4six92\n" +
            "18two977vgjrjxzck\n" +
            "jqqxone3mljbhvljqrjdtgcbvfncbzh\n" +
            "njcftck5tljbtwobvnsrxbqbeight46\n" +
            "sbgktxksdgzgz7jxjnvqg4seven7\n" +
            "sng1fivefourfourtwo9\n" +
            "4bcdqqccslg\n" +
            "ldq89nqkpnhzzmlfsbvjnbsqxbxthreegvnlqgbmnine\n" +
            "sevenn2twotwoprtsjchqpvhz9\n" +
            "6kmtqdphnninenbvqh3hnzdpxzpgfjfrbtrvr\n" +
            "271\n" +
            "4sevenonenhhkclrbk\n" +
            "mk1ttq\n" +
            "svfnqninefive3eightsix67\n" +
            "tcpkbglgzxstfldpkfvtwo4njhmtbjzm\n" +
            "hpdttc53eight6eightworsc\n" +
            "qpc891\n" +
            "mhpjlxxfbtbfqlgfivejrptpcgjh96\n" +
            "fvqlc1six\n" +
            "8twovhdfgzjp9ksb\n" +
            "sevennineskcdmgcscdrcj5hmnvtwo7kbtlvhll\n" +
            "eightcljvvvfbcslmpcnsl55hkjmktt\n" +
            "7eight9fives\n" +
            "45twothreenine6twot\n" +
            "49ktklntgtwonehgp\n" +
            "nine76gjxcrh9nine\n" +
            "four2eight\n" +
            "eightthreefivevpn2czkxfbc7nine\n" +
            "b12kbqkmtjjttnsjnz\n" +
            "6ninefivegn\n" +
            "3rt4rbcrqfourfour\n" +
            "365fivebstsvkjgteight7\n" +
            "vjrsmlbpfrttcsfg1\n" +
            "7nineseven\n" +
            "761tgrjvdnvzbdcbhbcjeight4\n" +
            "bhxsnhdseveneight4sevenfourfourfiveseven\n" +
            "45lfbzmjmbj2oneeightsix\n" +
            "5fourmsvb9kcmhvv75\n" +
            "trjjjgrhc3seven5\n" +
            "ntlpftjjjjtwonine4\n" +
            "3six91six\n" +
            "srmkpbx99db2kpqhkcrphhhrfjd\n" +
            "3mks3mtfhhzkfkkhftkbc\n" +
            "j68fourn\n" +
            "4five8three8nvhrm7\n" +
            "7vjlntbxzrqttjssbsb9sevenqsevenone\n" +
            "4onejkmnvrstthnkdtqm92\n" +
            "nvfhzndthreegvmgjkl93two4\n" +
            "ckk9\n" +
            "dqxnngrdpgngszsljponethree2gmnjjpktpvnine2\n" +
            "3pvhptkjs79\n" +
            "sixtsxstktchkzvqmpzfive5rbsvvqtwo\n" +
            "71hdkbm\n" +
            "3l1sixjndvmlgc\n" +
            "fiveninefive3fivetltsbgtwoxh\n" +
            "lneightthreelqskttgnkrfktnnr2two\n" +
            "5threeglcgtjqmf\n" +
            "7gmmvlkbrsevenkxhccfnkmmtlrjtktkzspjkstvbdqhq7one\n" +
            "zqdlfcdthlmjkjzdcmmnnineeight1\n" +
            "twosix2pnql\n" +
            "542nine5nine5\n" +
            "8sevenlbgfivej\n" +
            "five5fslhcxdvkhq6fourdjbmzc9\n" +
            "twoninethree1cpvqhkdvflmr5eightseven\n" +
            "seven1threeonethree6\n" +
            "2sevenzseven4xninesix9\n" +
            "x7ccfj8ninethree2one\n" +
            "1cqbrjcncrstqkthreethreesevenffive\n" +
            "tflsnvfchrxcglnzpxp2njkzvrvpfour3one\n" +
            "three5tkfvxxrpceight86khcqbnjjsixeight\n" +
            "tzcskpsixsix7xlnrd3bb\n" +
            "3seven3five9\n" +
            "fourninetwo9nmvlprcprtzmmg\n" +
            "88pxd99zhhh9\n" +
            "qdt9fourrztlcsbhvkqrtzkk\n" +
            "xqeightwothree9119qmhdltcmvdmxzvsix\n" +
            "xkkdzfzone3six22\n" +
            "5eightlninengqskzx\n" +
            "onekr3five3jkxrqdlvqhr6\n" +
            "fhnlbzqhltwo6three\n" +
            "qxgdqf779\n" +
            "33one29k\n" +
            "9one69dvnxsrqd\n" +
            "five2rzgfh\n" +
            "sevennlfdxpqseven74\n" +
            "four19four\n" +
            "onelpxlgcshrxspbgrvsgxvlzsj6two\n" +
            "mxbsixsixsixfmhrgone1eight\n" +
            "ninesix5one\n" +
            "threefour2ncbchnfnine9\n" +
            "4nine6gstzmsjndcthree4cmrhgnnq\n" +
            "1oneznvhbdtmjxktbc4seven\n" +
            "ttlfbpgjh6\n" +
            "qnftwone7\n" +
            "ncfplkcthreesevenninemrxxcx7\n" +
            "3bxpkseven434foureight1\n" +
            "5kmfr9threeonesix4rnneight\n" +
            "fxstzpjmjt85bsvlfktflq348\n" +
            "eighteight8tzqm\n" +
            "4sevenbkknfzshr9hkphkg\n" +
            "8rjsh9\n" +
            "pxvlpc5lf7jnmtprk61\n" +
            "qmkhqnlp8fourzjbdrthree9\n" +
            "seven5tlcthreethree75\n" +
            "3lkxlfzk\n" +
            "one12bkxtnxrsrg1\n" +
            "seven6six\n" +
            "ninethreezz2five\n" +
            "tmgmz6fbffftcstwotwoeight\n" +
            "fivelrmgkjcmdv2twogzljrklcg4\n" +
            "2bmgrtf\n" +
            "nvpftbs9one4mpdeight\n" +
            "rrgdzbhrx82cctzm\n" +
            "two3gbxcmdzxfive\n" +
            "8nine237rgrpfnztwosixfive\n" +
            "6rfqjgfzfcjccr5\n" +
            "86nndqtbpgz8\n" +
            "fourone8\n" +
            "vvzxhzxndbone57cmsrmxdlvgx\n" +
            "6onesixninethree\n" +
            "9fourprkvkvnczdk9\n" +
            "f3qkjjlvkcps13two2cgqjrptz\n" +
            "ftsevenglksjf38r7\n" +
            "vczfghj4hdseveneightfour\n" +
            "rltwone5jqszprf2six\n" +
            "1ninemjvkrghtnine\n" +
            "6one6pvjgrmtjmzgsqbgrdhclr71\n" +
            "11hp2bbhjcxthreenineonenine\n" +
            "hjhlngdtxmqseight8tqbtzgtnd\n" +
            "grkxvnqhnzthreefive6tqptwo\n" +
            "2sxpjpp9dqvvpbz85six\n" +
            "7onezpqjzmdmdclv9seven\n" +
            "onefourfourkrxvpbkrxxfbcsmr8gkbrrktbsix\n" +
            "8pjnnkhhrppeight25\n" +
            "2five9onethreejvnnzfourtwonefr\n" +
            "7ninesevenfourq\n" +
            "hpztwoseven2\n" +
            "nine5four4twofiveonexct9\n" +
            "5twodklsrzsix6\n" +
            "19pvhtmgvssdpz7five7five\n" +
            "495dxsmf4reightvmpvc\n" +
            "ckccxpxcp6five749\n" +
            "tvpzsix18four4\n" +
            "65sevenfiveqvcrbfourhmbf\n" +
            "833gtqpszrknllzc\n" +
            "4sevensix\n" +
            "ttjnbfd2gqkgfive\n" +
            "feighthzhtwoone6three2\n" +
            "one19twodxvdnkgcr1nhlmcjqcsrdcx\n" +
            "bdvrxkcltwoqsevensix2\n" +
            "1fmqfive8\n" +
            "eightcjhngkdmbponevqgshhj4four\n" +
            "gjpprh3eightcnpbtskmpponexrxfivesgprhdkx3\n" +
            "3tgmsbxsntv\n" +
            "7ksrhqknxsixqrjbseventvrsxrbnzv\n" +
            "3vdrzmnxp\n" +
            "nineseventhreesrxzjmdh3pfdgzdbdrgps4two\n" +
            "fourk73nine5xfctncone\n" +
            "zbtsrtcczn51twofourplxptsk\n" +
            "fiver296\n" +
            "mbmtrmvbfiveeight6\n" +
            "nine1156\n" +
            "vmppxzgsvbcstvfqd2\n" +
            "nine419thjfggone6\n" +
            "6threefourfourseventhree\n" +
            "tdtdxczbxrthreerdxzksix9oneights\n" +
            "qcx18qfivetwo54hklzzzk\n" +
            "five9two\n" +
            "2sixvzbljmbdqqzbch3\n" +
            "3xseveneightbcqgjk\n" +
            "7p7qqtssffh57\n" +
            "5fivezkg\n" +
            "foureight1nine\n" +
            "zbjgnine3onejdzjtbfivesixjs\n" +
            "sv8g2five7\n" +
            "eight7twolt1\n" +
            "1fiveeightthree27\n" +
            "6twobmqplkv6\n" +
            "7mmvq\n" +
            "sixxvjdzclvpqj7zpcpzdfzjfivekmjqtzmvsfnzrsm\n" +
            "2pdkfhpkff8\n" +
            "fhskqtwoseven8four8hksjpvntr\n" +
            "9kqzczkflbdxp5xzxdqdgsix9\n" +
            "5zckqcm6lxhzxtjhsqbrjjb\n" +
            "kxjrkvf46twovbflfbjbsixvntvcchdthree\n" +
            "3rbdbvmmqbninetwo359\n" +
            "8six67\n" +
            "g17onesevenfourtwo\n" +
            "fivethreeeightseven19five\n" +
            "8seven5sevenh7twoncbjrlbsjtwo\n" +
            "three7fivethree2fourhkfbcz\n" +
            "three8dggjtk5fivefiverkctnine\n" +
            "kxn6426qcdvhnmjsgj\n" +
            "three8dssix\n" +
            "nine2chbxhqclhf56\n" +
            "72hnjmbsdtzeight29\n" +
            "fivelvxxdeight9dkjdhtd\n" +
            "21ghjpseven\n" +
            "three1gkmlklfrchtjpfvlqmbsqtwonsix6\n" +
            "threeckvgbndgr56xphxnlfm3\n" +
            "ctqqgvznsixfqfgc1rhctvvqxnxlrthreehjjtchk\n" +
            "6cpfnqthctd\n" +
            "jbsvjcfds1three8onesldppzbxh\n" +
            "eightgfhrxtvcsg38\n" +
            "fkrzkgg5m\n" +
            "ztxlljfslg5ztgfmbzcgnsbxkbsoneqvphnzgmg3\n" +
            "five7foursevendrcrff3hfdqffhzjk\n" +
            "8sixfour9\n" +
            "threeeightnine9\n" +
            "vpqhvlppldcntxtwo7mxdptmgvp8sevenndqmfgrfour\n" +
            "vtpmjrhktdfouronesxxkrkdxf9seven\n" +
            "twothreetwo9twonchzd1one\n" +
            "eight7bppcdn\n" +
            "six3threesix3xclphmsbs48\n" +
            "fivemhpdttg7bs\n" +
            "ftpthreepqjdtqlmr9\n" +
            "nineone2\n" +
            "onecvninenine9kxmhzmh\n" +
            "1llghdnx\n" +
            "6sixhjqeightfour2five\n" +
            "five29sixeightlzzhxvmnnhxqrmpvczlfsljdmvb\n" +
            "8seven6seven5\n" +
            "3five18four2five\n" +
            "ndhsdrdrqllh43two3four1kgtdxdj\n" +
            "fpjzzkdvseventwo5\n" +
            "2npqgrs3six\n" +
            "ronenqbvbcjsjxrpphq6threetxkqq\n" +
            "k5six536eight5\n" +
            "7fourtfmeightvdzbd5\n" +
            "qds857twonesc\n" +
            "qscvcllfnz31mhfqvt\n" +
            "onetwocjnz6vprnd\n" +
            "onesix1\n" +
            "six6onenvh\n" +
            "twoxdmnvdnrd3smlzkbrqcvonekgzlbjgvnlpcvclcv2\n" +
            "jmhftwoqgfns9sevenjxgmmrsldlzmpz\n" +
            "fczkrsphfknkf4one93threetwoned\n" +
            "lfeightwoxcnvbrrqjnone8five\n" +
            "tpqhpxxtmhscvzzcrvnmkh2grq7\n" +
            "5k7three7\n" +
            "fourzfgttcflph239seven5five\n" +
            "8sevenseveneightvgfdkdglq89\n" +
            "nplmgprvtxfdjdlrdvnsffcxgdsln6\n" +
            "ninethree8onetwohfrbjclfx3ptxgdvnng\n" +
            "cftxznvnmgdtzrqvqtwofour145\n" +
            "1oneeight64\n" +
            "2pvvtpzpktjnine5phrthree8three\n" +
            "lchqzhdn1\n" +
            "foureightvxvf7vpzkgrkvk5zvlhnpdrvfoureightwoxz\n" +
            "lp7shzrbmzfivemrknxcfxbmbkplzhnbtdvsjqthree\n" +
            "fourfourthreemhccp4\n" +
            "jlcnfsixsix8sixfour99\n" +
            "three5seventhreexsbbrmlnqb9fourqqbcrg9\n" +
            "tkrjllccbqgtgvthx5three\n" +
            "eightthreenine5mv3two5four\n" +
            "mpxhm38njdsnls8nine9sgck\n" +
            "11sixtwo4bf6five3oneightj\n" +
            "djkfjcsix8eightkqvqrxghsphfnz\n" +
            "pcspdk896sixldtxqdd3one\n" +
            "three2dhzmdggcgs9pgbpvhjtlnineoneseven\n" +
            "qztxtbp43onethreejmmxbmv31\n" +
            "mcvmtn4three7four\n" +
            "vf92nbcqxznrgfour6\n" +
            "three12\n" +
            "28hh\n" +
            "jdkdsqkone3fourtwo62\n" +
            "79dgsjdsnfrkrbng\n" +
            "sevenninetwo62\n" +
            "threelfvclbbnpknrfive4\n" +
            "twothree8five9kqkzjcqxmt2nine8\n" +
            "feightwothree7nine4lddn\n" +
            "tsljmdxlfhgsgkbone9nineseven7rrxqqh\n" +
            "ftnplzthree32dcjtq\n" +
            "ninemzvxnine7zt6\n" +
            "four56sixfiveftzxcfqltbtprs\n" +
            "eightpggxhkthnine9chk\n" +
            "nzcxrvtc13fndpcvzjhcfrfmqsfourfgchxqgbzc9\n" +
            "pcgpcqtklcc4\n" +
            "4846onetwo3\n" +
            "fkpbcj2six2\n" +
            "pxsj33five1four5eighttwo\n" +
            "6five7fourdccz468five\n" +
            "hrbsxclgnsdzfcpdltkp9l7\n" +
            "twomhll7sxjtwoone7dhzbhphlpmlhx\n" +
            "sbfsrtbxsz7mqfklj\n" +
            "three7jhhpqgvtsixf\n" +
            "3dklxkgzn27pqvqhgseven7\n" +
            "lmlfive39twocvsdr2\n" +
            "three2rtlcxqnbjj8fourhsevenbkmvpdone\n" +
            "two1qzhpz\n" +
            "twosevenninet6551\n" +
            "9seventhree18\n" +
            "xqkskdzsninefrdsjcxbklg6five9\n" +
            "pxgzkvmgvmxshtstmfiveone51jhphcplgmzsix5\n" +
            "pkzrslhqtrscvc7\n" +
            "4one1three7nfgrcdone4xspqs\n" +
            "9273six24five\n" +
            "2qtwo\n" +
            "eightsgcgqzcfcgfourxqeightf46\n" +
            "teightwo786fourdll7\n" +
            "nqvqfszmtlzqvtrzpmg6qrgfqvjf5ksqhtn8\n" +
            "fivethreeninefournine42\n" +
            "23ninefivefivethreesix\n" +
            "jxmtpvxnbmzhddgtkqrone6bqbr\n" +
            "vxlfncmtnqeightbndmcgqpxx1mllgshkmcf\n" +
            "sevenxrlqpdh9ffourggbfpxgjrnrp\n" +
            "8onevllkmtlqc\n" +
            "kncjh84db\n" +
            "hzlfdgqzq93dgfgszfvdtffxrvrt7pzf\n" +
            "7six4one39\n" +
            "krmeightwofourkzrceightsevensevenfffnnnp1two\n" +
            "73bb3vjd\n" +
            "7eightthreefourjqjzpzdns6cfvcfvxcsix\n" +
            "lptfgxddt8gmdmmlj5ncpktzrstzjqpb5six\n" +
            "hsvgrjxbfqcsixlmztqfcr8\n" +
            "eight6dddfjxnsd2jfhfctpng\n" +
            "eight6sevenhzrfournine3\n" +
            "honeight9eight691xx57\n" +
            "khnspnpj711qmzvxmqninefkgfzhdpseven\n" +
            "9eightseveneightrsg3two\n" +
            "bc6vstkhczdnt45\n" +
            "1oneightl\n" +
            "eight9zfbcmr\n" +
            "ninebshsgplgfqpnctzhdr7\n" +
            "1fourninenineone\n" +
            "fourfive79\n" +
            "5gkmdxtmbonesixfive5five9\n" +
            "htxlqrxlphnine4four1\n" +
            "6fivetwo\n" +
            "one6fivegr8jhpkgkdzxd22q\n" +
            "6ninekdpgtnksxbhllvrzln\n" +
            "vvdgtcflxthree4eightsdxrbdf23\n" +
            "2six2sjtwohpvxsmfbpmpp4\n" +
            "blclfqtpfiveseventhreens3one2one\n" +
            "jvqthreehkzmbngll61rzvpr92bghvdvszh\n" +
            "pcthreeseventhreeninethreefive2one\n" +
            "89seven1\n" +
            "ztwonesix9\n" +
            "conemvksxxdthseven1lmfmppzttqnn\n" +
            "six6four\n" +
            "threefourxct5bvvkpgpgjqvlzv\n" +
            "gsjrdgxfv38\n" +
            "fivenrlgnrnms1\n" +
            "tvtwonenine9rhs6five56\n" +
            "kgnineczjhrfive45hhxhtxltdqfive\n" +
            "sixfiveseven17six16bv\n" +
            "5vxqvtsltcbjrdrct3fourtwotwobgsnkszmbd\n" +
            "42three7\n" +
            "btdbbtqb89dneight34\n" +
            "htninesevensixninetwo4mnmd\n" +
            "jgzdlf22qnqdr9bqczsfx\n" +
            "zfvf296fj\n" +
            "fivejjvtjp4fghtgplkjnine36\n" +
            "3rxfbrpmtkcrrsjg\n" +
            "twopdxltmnv2seven\n" +
            "2fourgmjfdgh\n" +
            "2threerfjsgfdlhheightfive\n" +
            "4cvmkr\n" +
            "68cd\n" +
            "6two2\n" +
            "onetwoeight6eightsix\n" +
            "1five5sevenrhsl229\n" +
            "4sixbcxmgvfourjsqkc85eight8\n" +
            "4two41pqfnbfvqqr3twodzjntlxmkhzcr\n" +
            "gqzksmprzm8llggmhbmlgnpqg\n" +
            "8xbseven6dbtsd9plxhhjznf25\n" +
            "twoonefivepdflr7cggfvvtfour\n" +
            "jhpcqpqnine5twofive1stjhmdfjone\n" +
            "6nineninetbjr68xczndt\n" +
            "2fvdcvhgskrbnqqjgmvpcseven\n" +
            "3pnhgzzfk9nine\n" +
            "pzrs8three8sixtwotwo\n" +
            "79five6\n" +
            "nineeight1glknld1onefiveskcjmn3\n" +
            "2gmdqptlfpone5\n" +
            "onethreeseven881ninezzkhqnbb\n" +
            "nine2pznvckk462hhpbone3\n" +
            "ninecpjhzn9\n" +
            "xhxdkkpxrkl8seven7\n" +
            "four345five143\n" +
            "7eightthreebhckgdsmdd7twonefj\n" +
            "4cvcmdbjfk4nctxzdkznh8\n" +
            "kdzd2dxknpninethnpktjdsskgzpseven\n" +
            "fiveninefivefive1\n" +
            "ghqlddsdrrzjddsbr9eight\n" +
            "4twolmjssn\n" +
            "bzzlthxrjkgthree1ninedk5three1\n" +
            "68two2cjrjn9sixbzeight\n" +
            "fourtkc9teightfive6nine\n" +
            "3six3\n" +
            "1dhhznrxxdz4onedbsjmkqnv\n" +
            "seventhreesix8twohjdhjoneeightsix\n" +
            "two4twofourone1tfpbpqldqgthree1\n" +
            "ddtgjzzlsrvtwofourdvdvtbfv9six\n" +
            "26tfrfptjg7lnqcmninefivejlrmlnsthree\n" +
            "six633two32\n" +
            "four58spslgtdh3nkpcgdxbrqx7\n" +
            "5four57vgcvlxmxlmdnmcs\n" +
            "dmcdgcnine75pzlh\n" +
            "12threexczfive6six3\n" +
            "1onevpntrrkggtjzsvktxxprsthd\n" +
            "kntxrpjqtl7fourfourqvsgq3seven\n" +
            "bdbfk269jsixsbhpjhvgvzvnfmp\n" +
            "seven1nine2four6rvv\n" +
            "eightzzxgdhsfnp5seven6eight2szsseven\n" +
            "two8three\n" +
            "jltv47\n" +
            "fivevdhgg5two1hpnjlvkeighttwo\n" +
            "sxsevensevenpmpjjvdlr9f5eight\n" +
            "8qntwokkffvkrlgoneightfnm\n" +
            "eight5six\n" +
            "twothree1eight\n" +
            "nineone7\n" +
            "1cgqmqxxdp8sixeight\n" +
            "2hbgmzcxtwothree1\n" +
            "1gjzk\n" +
            "2jrkzdsfvzc\n" +
            "five84jlxljnqqbfqlninethree\n" +
            "rxbdxskdsevenltqgkbkxone5nineonemxgctrc\n" +
            "ltxxfvpssbfivekxx7two78jrkdxfxk7\n" +
            "1eightonefiveone7\n" +
            "zhstjzhone1\n" +
            "fhrxonehjqzvkdm2six\n" +
            "xhtgntqlvxhjtr4ninesdbvfmqkr\n" +
            "3two4nvljffhjd4fiveml\n" +
            "9gtzflksmfourthree4threef\n" +
            "bsbpqtzsttwo65zkdsg8twojxgrxkrc\n" +
            "eightqlnmzvhjmjkntk6eight2\n" +
            "nine9sevenfourtwopl7\n" +
            "9tlninezttdrbkxxrkrxzzkffone\n" +
            "9zngoneoneightzdz\n" +
            "jdj3\n" +
            "fjeightworxkskbrbtmgqqqxchvfbvxctthreetgq7\n" +
            "11nscpbfour\n" +
            "onespnbfninetgqmtbdmr17pmjt\n" +
            "tpqvr1gcrth7gkld\n" +
            "nineeight6khkrgsdcfpkcjkglbq5lxkjxsvrrktmfzsbz\n" +
            "4twozgxqjbdsone963two\n" +
            "6mxgxnjb\n" +
            "495seven\n" +
            "threeseven4\n" +
            "vghlvmp7four6two7\n" +
            "2twofourrbldqvfkvgzqrblmrkzr\n" +
            "hldlhninecllnsix7\n" +
            "5zpcvzmngvxrcvxncxgf7one\n" +
            "twoseven3pgdtdxpxsixnbrmnzndmgone1\n" +
            "94six8329\n" +
            "xkgjdg8\n" +
            "5gzxngzb2twohkrdjqkmgsl83\n" +
            "9nzfgp\n" +
            "15xrgxm7\n" +
            "3nineonermn\n" +
            "vggvnhqkjseventwo4onetwonftrnd\n" +
            "9514sqst62\n" +
            "mxhnceightfiveftmcdpgv63two6four\n" +
            "nine6five181\n" +
            "sevenbsixsbzmone55\n";

    private static final String test = "two1nine\n" +
            "eightwothree\n" +
            "abcone2threexyz\n" +
            "xtwone3four\n" +
            "4nineeightseven2\n" +
            "zoneight234\n" +
            "7pqrstsixteen";

    public static void main(String[] args) {
        String[] inputArray = input.split("\n");
        int total = 0;

        for (int i = 0; i < inputArray.length; i++) {
            String toTest = inputArray[i];

            char[] toTestArray = toTest.toCharArray();

            String first = "";
            String last = "";



            for (int j = 0; j < toTestArray.length; j++) {
                char c = toTestArray[j];

                if (isNumeric(c)) {
                    if (first.isEmpty()) {
                        first = String.valueOf(c);
                    }

                    last = String.valueOf(c);
                }

                int digit = digitFromString(toTest.substring(j));

                if (digit != -1) {
                    if (first.isEmpty()) {
                        first = String.valueOf(digit);
                    }

                    last = String.valueOf(digit);
                }
            }

            int value = Integer.valueOf(first + last);
            total += value;
        }
        System.out.println(total);
    }

    public static boolean isNumeric(char c) {
        try {
            Integer.parseInt(String.valueOf(c));

            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    public static int digitFromString(String s) {
        if (s.startsWith("one")) {
            return 1;
        } else if (s.startsWith("two")) {
            return 2;
        } else if (s.startsWith("three")) {
            return 3;
        } else if (s.startsWith("four")) {
            return 4;
        } else if (s.startsWith("five")) {
            return 5;
        } else if (s.startsWith("six")) {
            return 6;
        } else if (s.startsWith("seven")) {
            return 7;
        } else if (s.startsWith("eight")) {
            return 8;
        } else if (s.startsWith("nine")) {
            return 9;
        }

        return -1;
    }
}
